import { html } from 'hono/html'
import { Layout } from './layout'
import { Panel, StatCard, IconButton } from './components'
import type { Inbox } from '../db/queries'

export function DashboardPage({ 
  inboxes, domains, apiKeys, totalInboxes, totalMessages, currentPage, apiKeyFilter
}: { 
  inboxes: Inbox[]; domains: string[]; apiKeys: any[]; totalInboxes: number; totalMessages: number; currentPage: number; apiKeyFilter?: any
}) {
  const totalPages = Math.ceil(totalInboxes / 20) || 1
  const baseUrl = apiKeyFilter ? `/dashboard/apikeys/${apiKeyFilter.id}` : '/dashboard'

  return Layout({
    title: apiKeyFilter ? `Filtered by API Key` : 'Dashboard',
    session: true,
    children: html`
    <div class="dash-header">
      <div>
        <h2>${apiKeyFilter ? `API Key: ${apiKeyFilter.keyValue}` : 'Dashboard Overview'}</h2>
        <p>${apiKeyFilter ? `Showing ${totalInboxes} inboxes generated by this key` : 'Manage all disposable inboxes and API keys'}</p>
      </div>
      ${apiKeyFilter ? html`
        <a href="/dashboard" class="btn-primary" style="text-decoration:none"><i data-lucide="arrow-left" class="icon-inline" style="color:white;margin:0 8px 0 0"></i> Back to Dashboard</a>
      ` : ''}
    </div>

    <div class="stats-grid">
      ${StatCard({ label: 'Total Inboxes', value: totalInboxes })}
      ${StatCard({ label: 'Total Messages', value: totalMessages })}
      ${StatCard({ label: 'Active Domains', value: domains.length })}
      ${StatCard({ label: 'API Keys', value: apiKeys.length })}
    </div>

    ${!apiKeyFilter ? Panel({ title: 'API Keys & Permissions', icon: 'key', children: html`
      <form class="api-key-box" onsubmit="createApiKey(event)">
        <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px">
          <div class="segmented-control">
            <label class="segmented-btn active" id="scope-btn-all">
              <input type="radio" name="domainScope" value="*" checked onchange="handleScopeChange('*')" style="display:none" />
              <i data-lucide="globe" class="icon-sm"></i> All Domains (*)
            </label>
            <label class="segmented-btn" id="scope-btn-specific">
              <input type="radio" name="domainScope" value="specific" onchange="handleScopeChange('specific')" style="display:none" />
              <i data-lucide="filter" class="icon-sm"></i> Specific Domains
            </label>
          </div>

          <div style="display:flex;align-items:flex-end;gap:10px;flex-wrap:wrap;">
            <div style="width:130px;">
              <label style="font-size:0.75rem;color:var(--text-dim);display:block;margin-bottom:4px">Max Inboxes (0=∞)</label>
              <input type="number" id="maxInboxes" placeholder="0" min="0" value="0" style="width:100%;padding:6px 10px;font-size:0.85rem;" />
            </div>
            <div style="width:130px;">
              <label style="font-size:0.75rem;color:var(--text-dim);display:block;margin-bottom:4px">Max Msgs (0=∞)</label>
              <input type="number" id="maxMessages" placeholder="0" min="0" value="0" style="width:100%;padding:6px 10px;font-size:0.85rem;" />
            </div>
            <button type="submit" class="btn-primary" id="btnCreateKey" style="padding:7px 18px;font-size:0.85rem;height:34px">
              <i data-lucide="plus" class="icon-sm"></i> Generate Key
            </button>
          </div>
        </div>
        
        <div id="specificDomains" class="domain-badge-grid" style="display:none">
          ${domains.map(d => html`
            <label class="domain-tag">
              <input type="checkbox" name="selectedDomains" value="${d}" onchange="toggleTag(this)" style="display:none" />
              <i data-lucide="check" class="icon-sm tag-check" style="display:none"></i>
              <span>${d}</span>
            </label>
          `)}
        </div>
      </form>

      <div class="inbox-list">
        ${!apiKeys || apiKeys.length === 0 ? html`<p style="color:var(--text-dim);text-align:center;padding:20px">No API keys generated yet.</p>` : ''}
        ${apiKeys && apiKeys.map(k => html`
          <div class="inbox-item" id="keyrow-${k.id}">
            <div class="inbox-info">
              <div style="display:flex;align-items:center;gap:10px;margin-bottom:6px">
                <span style="font-family:monospace;font-weight:600;font-size:1.05rem;color:var(--primary)">${k.keyValue}</span>
                <button type="button" class="btn-icon" onclick="copyKey('${k.keyValue}')" title="Copy Key" style="padding:2px">
                  <i data-lucide="copy" class="icon-sm"></i>
                </button>
                <span style="background:rgba(16,185,129,0.1);color:#10b981;border:1px solid rgba(16,185,129,0.2);padding:2px 8px;border-radius:12px;font-size:0.7rem;font-weight:600">Active</span>
              </div>
              <div style="display:flex;flex-wrap:wrap;gap:8px;align-items:center">
                <span class="key-chip">Domains: <strong>${k.permittedDomains}</strong></span>
                <span class="key-chip">Inboxes: <strong>${k.maxInboxes > 0 ? k.maxInboxes : '∞'}</strong></span>
                <span class="key-chip">Messages: <strong>${k.maxMessages > 0 ? k.maxMessages : '∞'}</strong></span>
                <span style="font-size:0.75rem;color:var(--text-dim);margin-left:4px">${new Date(k.createdAt).toLocaleDateString()}</span>
              </div>
            </div>
            <div class="actions">
              <a href="/dashboard/apikeys/${k.id}" class="btn-icon" title="View Generated Inboxes"><i data-lucide="eye"></i></a>
              ${IconButton({ icon: 'trash-2', onclick: `delKey('${k.id}')`, title: 'Revoke Key', variant: 'danger' })}
            </div>
          </div>
        `)}
      </div>
    `}) : ''}

    ${!apiKeyFilter ? Panel({ title: 'Create Custom Inbox', icon: 'plus-circle', children: html`
      <form class="create-form" onsubmit="create(event)">
        <div class="input-group">
          <input type="text" id="local" placeholder="random (optional)" />
          <span class="at">@</span>
          <select id="domain">
            ${domains.map(d => html`<option value="${d}">${d}</option>`)}
          </select>
        </div>
        <button type="submit" class="btn-primary" id="btnCreate">Create Inbox</button>
      </form>
    `}) : ''}

    ${!apiKeyFilter ? Panel({ title: 'Generated Inboxes Management', icon: 'inbox', children: html`
      <div style="padding:16px; text-align:center; background:rgba(255,255,255,0.02); border-radius:8px; border:1px solid var(--border)">
        <p style="color:var(--text-dim); margin-bottom:16px;">
          View and manage all disposable inboxes created by API Keys or custom creation.
        </p>
        <a href="/inboxes" class="btn-primary" style="display:inline-flex; text-decoration:none;">
          <i data-lucide="list" class="icon-sm" style="margin-right:8px"></i> View All Inboxes
        </a>
      </div>
    `}) : Panel({ title: 'Generated Inboxes', icon: 'list', children: html`
      <div class="inbox-list">
        ${inboxes.length === 0 ? html`<p style="color:var(--text-dim);text-align:center;padding:20px">No inboxes yet.</p>` : ''}
        ${inboxes.map(i => html`
          <div class="inbox-item" id="row-${i.address}">
            <div class="inbox-info">
              <h4><a href="/inbox/${encodeURIComponent(i.address)}">${i.address}</a></h4>
              <p>Created: ${new Date(i.createdAt).toLocaleString()}</p>
            </div>
            <div class="inbox-meta">
              <span class="badge">${i.messageCount || 0} msgs</span>
              <div class="actions">
                <a href="/inbox/${encodeURIComponent(i.address)}" class="btn-icon" title="View Inbox"><i data-lucide="eye"></i></a>
                ${IconButton({ icon: 'trash-2', onclick: `del('${i.address}')`, title: 'Delete', variant: 'danger' })}
              </div>
            </div>
          </div>
        `)}
      </div>

      ${totalPages > 1 ? html`
      <div style="display:flex; justify-content:center; align-items:center; gap:16px; margin-top:24px; padding-top:16px; border-top:1px solid var(--border)">
        <a href="${baseUrl}?page=${currentPage - 1}" class="btn-primary" style="${currentPage <= 1 ? 'pointer-events:none;opacity:0.5' : ''}">
          <i data-lucide="chevron-left" class="icon-inline"></i> Prev
        </a>

        <span style="color:var(--text-dim); font-size:0.9rem;">
          Page <strong>${currentPage}</strong> of ${totalPages}
        </span>

        <a href="${baseUrl}?page=${currentPage + 1}" class="btn-primary" style="${currentPage >= totalPages ? 'pointer-events:none;opacity:0.5' : ''}">
          Next <i data-lucide="chevron-right" class="icon-inline" style="margin-left:8px; margin-right:0"></i>
        </a>
      </div>
      ` : ''}
    `})}

    <script>
      function showToast(msg) {
        const t = document.getElementById('toast');
        t.textContent = msg; t.classList.add('show');
        setTimeout(() => t.classList.remove('show'), 3000);
      }

      function handleScopeChange(scope) {
        const container = document.getElementById('specificDomains');
        const btnAll = document.getElementById('scope-btn-all');
        const btnSpecific = document.getElementById('scope-btn-specific');
        if (scope === 'specific') {
          container.style.display = 'flex';
          btnAll.classList.remove('active');
          btnSpecific.classList.add('active');
        } else {
          container.style.display = 'none';
          btnAll.classList.add('active');
          btnSpecific.classList.remove('active');
        }
      }

      function toggleTag(cb) {
        const tag = cb.closest('.domain-tag');
        const check = tag.querySelector('.tag-check');
        if (cb.checked) {
          tag.classList.add('checked');
          if (check) check.style.display = 'inline-block';
        } else {
          tag.classList.remove('checked');
          if (check) check.style.display = 'none';
        }
      }

      function copyKey(val) {
        navigator.clipboard.writeText(val);
        showToast('API Key copied');
      }
      
      async function create(e) {
        e.preventDefault();
        const btn = document.getElementById('btnCreate');
        btn.disabled = true; btn.textContent = 'Creating...';
        const local = document.getElementById('local').value;
        const domain = document.getElementById('domain').value;
        try {
          const r = await fetch('/dashboard/inboxes', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify({ local, domain })
          });
          if (r.ok) location.reload();
          else showToast('Failed to create inbox');
        } finally {
          btn.disabled = false; btn.textContent = 'Create Inbox';
        }
      }

      async function del(addr) {
        if (!confirm('Delete inbox ' + addr + '?')) return;
        const r = await fetch('/dashboard/inboxes/' + encodeURIComponent(addr), { method: 'DELETE' });
        if (r.ok) {
          const row = document.getElementById('row-' + addr);
          if (row) row.remove();
          showToast('Deleted ' + addr);
        } else {
          showToast('Failed to delete');
        }
      }

      async function createApiKey(e) {
        e.preventDefault();
        const btn = document.getElementById('btnCreateKey');
        btn.disabled = true; btn.textContent = 'Generating...';
        
        let domains = '*';
        const scope = document.querySelector('input[name="domainScope"]:checked').value;
        if (scope === 'specific') {
          const checked = Array.from(document.querySelectorAll('input[name="selectedDomains"]:checked')).map(cb => cb.value);
          if (checked.length > 0) domains = checked.join(',');
        }

        const maxInboxes = parseInt(document.getElementById('maxInboxes').value || '0', 10);
        const maxMessages = parseInt(document.getElementById('maxMessages').value || '0', 10);

        try {
          const r = await fetch('/dashboard/apikeys', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify({ domains, maxInboxes, maxMessages })
          });
          if (r.ok) location.reload();
          else showToast('Failed to generate key');
        } finally {
          btn.disabled = false; btn.textContent = 'Generate Key';
        }
      }

      async function delKey(id) {
        if (!confirm('Revoke this API Key?')) return;
        const r = await fetch('/dashboard/apikeys/' + encodeURIComponent(id), { method: 'DELETE' });
        if (r.ok) {
          const row = document.getElementById('keyrow-' + id);
          if (row) row.remove();
          showToast('Key revoked');
        } else {
          showToast('Failed to revoke');
        }
      }

      async function logout() {
        await fetch('/auth/logout', {method:'POST'});
        location.href = '/login';
      }
    </script>
    `
  })
}

