import { html, raw } from 'hono/html'
import { Layout } from './layout'
import { Panel, StatCard, IconButton, AnalyticsChartsGrid, DomainShowcaseWidget } from './components'
import type { Inbox } from '../db/queries'

export function DashboardPage({ 
  inboxes, domains, apiKeys, totalInboxes, totalMessages, currentPage, apiKeyFilter, domainStats = {}
}: { 
  inboxes: Inbox[]; domains: string[]; apiKeys: any[]; totalInboxes: number; totalMessages: number; currentPage: number; apiKeyFilter?: any; domainStats?: Record<string, number>
}) {
  const totalPages = Math.ceil(totalInboxes / 20) || 1
  const baseUrl = apiKeyFilter ? `/dashboard/apikeys/${apiKeyFilter.id}` : '/dashboard'
  const avgMsgsPerInbox = totalInboxes > 0 ? (totalMessages / totalInboxes).toFixed(1) : '0'

  // Build domain breakdown JSON for Chart.js
  const domainLabels = domains.length > 0 ? domains : ['Default']
  const domainData = domainLabels.map(d => domainStats[d] || 0)

  return Layout({
    title: apiKeyFilter ? `Filtered by API Key` : 'Dashboard',
    session: true,
    children: html`
    <div class="dash-header">
      <div>
        <h2>${apiKeyFilter ? `API Key: ${apiKeyFilter.keyValue}` : 'Dashboard Overview'}</h2>
        <p>${apiKeyFilter ? `Showing ${totalInboxes} inboxes generated by this key` : 'Manage all disposable inboxes, domain showcase, and system metrics'}</p>
      </div>
      ${apiKeyFilter ? html`
        <a href="/dashboard" class="btn-primary" style="text-decoration:none"><i data-lucide="arrow-left" class="icon-inline" style="color:white;margin:0 8px 0 0"></i> Back to Dashboard</a>
      ` : html`
        <div style="display:flex;align-items:center;gap:10px">
          <span style="font-size:0.85rem;color:var(--text-dim);background:rgba(16,185,129,0.1);border:1px solid rgba(16,185,129,0.25);padding:6px 14px;border-radius:20px;display:flex;align-items:center;gap:8px">
            <span class="pulse-dot"></span> System 100% Operational
          </span>
        </div>
      `}
    </div>

    <!-- SaaS Metrics Grid -->
    <div class="stats-grid">
      ${StatCard({ label: 'Total Inboxes', value: totalInboxes, subText: 'Active Disposable Addresses', icon: 'inbox', color: '#60a5fa' })}
      ${StatCard({ label: 'Total Messages', value: totalMessages, subText: `~${avgMsgsPerInbox} msgs / inbox`, icon: 'mail', color: '#34d399' })}
      ${StatCard({ label: 'Active Domains', value: domains.length, subText: 'Supported Mail Suffixes', icon: 'globe', color: '#38bdf8' })}
      ${StatCard({ label: 'API Keys', value: apiKeys.length, subText: 'Issued Access Keys', icon: 'key', color: '#a78bfa' })}
    </div>

    ${!apiKeyFilter ? html`
    <!-- SaaS Analytics & Distribution Charts -->
    ${AnalyticsChartsGrid()}

    <!-- Active Domain Showcase Widget -->
    ${DomainShowcaseWidget({ domains, domainStats })}
    ` : ''}

    ${!apiKeyFilter ? Panel({ title: 'API Keys & Permissions', icon: 'key', children: html`
      <div class="api-key-box" style="background:rgba(15,23,42,0.6);margin-bottom:20px">
        <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px">
          <div>
            <div style="font-size:0.75rem;color:var(--text-dim);text-transform:uppercase;letter-spacing:0.05em">API Base Endpoint URL</div>
            <div style="font-family:monospace;font-size:1rem;color:#38bdf8;font-weight:600;margin-top:4px" id="apiBaseUrlDisplay">loading...</div>
          </div>
          <button type="button" class="btn-primary" onclick="copyApiBaseUrl()" style="padding:7px 16px;font-size:0.85rem">
            <i data-lucide="copy" class="icon-sm"></i> Copy API Base URL
          </button>
        </div>
      </div>

      <form class="api-key-box" onsubmit="createApiKey(event)">
        <div class="api-key-form-controls">
          <div class="segmented-control">
            <label class="segmented-btn active" id="scope-btn-all">
              <input type="radio" name="domainScope" value="*" checked onchange="handleScopeChange('*')" style="display:none" />
              <i data-lucide="globe" class="icon-sm"></i> All Domains (*)
            </label>
            <label class="segmented-btn" id="scope-btn-specific">
              <input type="radio" name="domainScope" value="specific" onchange="handleScopeChange('specific')" style="display:none" />
              <i data-lucide="filter" class="icon-sm"></i> Specific Domains
            </label>
          </div>

          <div class="api-key-form-inputs">
            <div class="api-key-input-field">
              <label>Max Inboxes (0=∞)</label>
              <input type="number" id="maxInboxes" placeholder="0" min="0" value="0" />
            </div>
            <div class="api-key-input-field">
              <label>Max Msgs (0=∞)</label>
              <input type="number" id="maxMessages" placeholder="0" min="0" value="0" />
            </div>
            <button type="submit" class="btn-primary btn-generate-key" id="btnCreateKey">
              <i data-lucide="plus" class="icon-sm"></i> Generate Key
            </button>
          </div>
        </div>
        
        <div id="specificDomains" class="domain-badge-grid" style="display:none">
          ${domains.map(d => html`
            <label class="domain-tag">
              <input type="checkbox" name="selectedDomains" value="${d}" onchange="toggleTag(this)" style="display:none" />
              <i data-lucide="check" class="icon-sm tag-check" style="display:none"></i>
              <span>${d}</span>
            </label>
          `)}
        </div>
      </form>

      <div class="inbox-list">
        ${!apiKeys || apiKeys.length === 0 ? html`<p style="color:var(--text-dim);text-align:center;padding:20px">No API keys generated yet.</p>` : ''}
        ${apiKeys && apiKeys.map(k => html`
          <div class="inbox-item" id="keyrow-${k.id}">
            <div class="inbox-info">
              <div style="display:flex;align-items:center;gap:10px;margin-bottom:6px">
                <span style="font-family:monospace;font-weight:600;font-size:1.05rem;color:var(--primary)">${k.keyValue}</span>
                <span style="background:rgba(16,185,129,0.1);color:#10b981;border:1px solid rgba(16,185,129,0.2);padding:2px 8px;border-radius:12px;font-size:0.7rem;font-weight:600">Active</span>
              </div>
              <div style="display:flex;flex-wrap:wrap;gap:8px;align-items:center">
                <span class="key-chip">Domains: <strong>${k.permittedDomains}</strong></span>
                <span class="key-chip">Inboxes: <strong>${k.maxInboxes > 0 ? k.maxInboxes : '∞'}</strong></span>
                <span class="key-chip">Messages: <strong>${k.maxMessages > 0 ? k.maxMessages : '∞'}</strong></span>
                <span style="font-size:0.75rem;color:var(--text-dim);margin-left:4px">${new Date(k.createdAt).toLocaleDateString()}</span>
              </div>
            </div>
            <div class="actions">
              <a href="/admin/apikeys/${k.id}" class="btn-icon" title="View Generated Inboxes"><i data-lucide="eye"></i></a>
              ${IconButton({ icon: 'trash-2', onclick: `delKey('${k.id}')`, title: 'Revoke Key', variant: 'danger' })}
            </div>
          </div>
        `)}
      </div>
    `}) : ''}

    ${Panel({ title: 'Inbox Management', icon: 'inbox', children: html`
      ${!apiKeyFilter ? html`
      <form class="create-form" onsubmit="create(event)" style="margin-bottom:24px">
        <div class="input-group">
          <input type="text" id="local" placeholder="Random prefix if empty" />
          <span class="at">@</span>
          <select id="domain">
            ${domains.map(d => html`<option value="${d}">${d}</option>`)}
          </select>
        </div>
        <button type="submit" class="btn-primary" id="btnCreate">
          <i data-lucide="plus" class="icon-sm"></i> Create Inbox
        </button>
      </form>
      ` : ''}

      <div class="inbox-list">
        ${inboxes.length === 0 ? html`<p style="color:var(--text-dim);text-align:center;padding:20px">No inboxes found.</p>` : ''}
        ${inboxes.slice(0, 5).map(i => html`
          <div class="inbox-item" id="row-${i.address}">
            <div class="inbox-info">
              <h4><a href="/admin/inbox/${encodeURIComponent(i.address)}">${i.address}</a></h4>
              <p>Created: ${new Date(i.createdAt).toLocaleString()}</p>
            </div>
            <div class="inbox-meta">
              <span class="badge">${i.messageCount || 0} msgs</span>
              <div class="actions">
                <a href="/admin/inbox/${encodeURIComponent(i.address)}" class="btn-icon" title="View Inbox"><i data-lucide="eye"></i></a>
                ${IconButton({ icon: 'trash-2', onclick: `del('${i.address}')`, title: 'Delete', variant: 'danger' })}
              </div>
            </div>
          </div>
        `)}
      </div>

      <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:12px; margin-top:24px; padding-top:16px; border-top:1px solid var(--border)">
        <span style="color:var(--text-dim); font-size:0.875rem">
          Showing <strong>${Math.min(inboxes.length, 5)}</strong> of <strong>${totalInboxes}</strong> active inboxes
        </span>
        <a href="/admin/inboxes" class="btn-primary" style="text-decoration:none">
          <i data-lucide="inbox" class="icon-inline" style="margin-right:8px"></i> View All Inboxes (${totalInboxes}) <i data-lucide="arrow-right" class="icon-inline" style="margin-left:8px;margin-right:0"></i>
        </a>
      </div>
    `})}

    <dialog id="keyModal" class="confirm-modal" style="max-width:500px">
      <div class="confirm-icon" style="background:rgba(59,130,246,0.1)"><i data-lucide="key" style="color:var(--primary)"></i></div>
      <h3>API Key Generated</h3>
      <p>Save this key now. For security, it won't be shown again in full format.</p>
      <div style="background:rgba(15,23,42,0.8);border:1px solid var(--border);padding:14px;border-radius:var(--radius-sm);margin-bottom:20px;font-family:monospace;font-size:1rem;color:#60a5fa;word-break:break-all" id="newKey"></div>
      <div class="confirm-actions">
        <button class="btn-primary" onclick="copyGeneratedKey()"><i data-lucide="copy" class="icon-sm"></i> Copy Key</button>
        <button class="btn-cancel" onclick="document.getElementById('keyModal').close();location.reload();">Close</button>
      </div>
    </dialog>

    <script>
      // Domain Showcase Search Filter
      function filterDomainCards() {
        const query = document.getElementById('domainSearchInput').value.toLowerCase().trim();
        const cards = document.querySelectorAll('.domain-card-item');
        cards.forEach(card => {
          const name = card.getAttribute('data-domain').toLowerCase();
          if (name.includes(query)) {
            card.style.display = 'flex';
          } else {
            card.style.display = 'none';
          }
        });
      }

      function copyDomain(d) {
        navigator.clipboard.writeText('@' + d);
        showToast('Copied @' + d + ' to clipboard');
      }

      function showToast(msg) {
        const t = document.getElementById('toast');
        t.textContent = msg; t.classList.add('show');
        setTimeout(() => t.classList.remove('show'), 3000);
      }

      function handleScopeChange(val) {
        const container = document.getElementById('specificDomains');
        const btnAll = document.getElementById('scope-btn-all');
        const btnSpecific = document.getElementById('scope-btn-specific');
        if (val === 'specific') {
          container.style.display = 'flex';
          btnSpecific.classList.add('active');
          btnAll.classList.remove('active');
        } else {
          container.style.display = 'none';
          btnAll.classList.add('active');
          btnSpecific.classList.remove('active');
        }
      }

      function toggleTag(cb) {
        const tag = cb.closest('.domain-tag');
        const check = tag.querySelector('.tag-check');
        if (cb.checked) {
          tag.classList.add('checked');
          if (check) check.style.display = 'inline-block';
        } else {
          tag.classList.remove('checked');
          if (check) check.style.display = 'none';
        }
      }

      function copyGeneratedKey() {
        navigator.clipboard.writeText(document.getElementById('newKey').textContent || '');
        showToast('API Key copied');
      }
      
      async function create(e) {
        e.preventDefault();
        const btn = document.getElementById('btnCreate');
        btn.disabled = true; btn.textContent = 'Creating...';
        const local = document.getElementById('local').value;
        const domain = document.getElementById('domain').value;
        try {
          const r = await fetch('/dashboard/inboxes', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify({ local, domain })
          });
          if (r.ok) location.reload();
          else showToast('Failed to create inbox');
        } finally {
          btn.disabled = false; btn.textContent = 'Create Inbox';
        }
      }

      async function del(addr) {
        confirmAction('Delete Inbox', 'Are you sure you want to delete ' + addr + '? All messages will be lost.', 'Delete', async function() {
          const r = await fetch('/dashboard/inboxes/' + encodeURIComponent(addr), { method: 'DELETE' });
          if (r.ok) {
            const row = document.getElementById('row-' + addr);
            if (row) row.remove();
            showToast('Deleted ' + addr);
          } else {
            showToast('Failed to delete');
          }
        });
      }

      async function createApiKey(e) {
        e.preventDefault();
        const btn = document.getElementById('btnCreateKey');
        btn.disabled = true; btn.textContent = 'Generating...';
        
        let domains = '*';
        const scope = document.querySelector('input[name="domainScope"]:checked').value;
        if (scope === 'specific') {
          const checked = Array.from(document.querySelectorAll('input[name="selectedDomains"]:checked')).map(cb => cb.value);
          if (checked.length > 0) domains = checked.join(',');
        }

        const maxInboxes = parseInt(document.getElementById('maxInboxes').value || '0', 10);
        const maxMessages = parseInt(document.getElementById('maxMessages').value || '0', 10);

        try {
          const r = await fetch('/dashboard/apikeys', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify({ domains, maxInboxes, maxMessages })
          });
          if (r.ok) {
            const data = await r.json();
            document.getElementById('newKey').textContent = data.key;
            document.getElementById('keyModal').showModal();
          } else showToast('Failed to generate key');
        } finally {
          btn.disabled = false; btn.textContent = 'Generate Key';
        }
      }

      async function delKey(id) {
        confirmAction('Revoke API Key', 'Are you sure you want to revoke this API Key? Applications using it will immediately lose access.', 'Revoke Key', async function() {
          const r = await fetch('/dashboard/apikeys/' + encodeURIComponent(id), { method: 'DELETE' });
          if (r.ok) {
            const row = document.getElementById('keyrow-' + id);
            if (row) row.remove();
            showToast('Key revoked');
          } else {
            showToast('Failed to revoke');
          }
        });
      }

      function copyApiBaseUrl() {
        const url = window.location.origin + '/api';
        navigator.clipboard.writeText(url);
        showToast('API Base URL copied: ' + url);
      }

      // Initialize Chart.js Charts
      window.addEventListener('DOMContentLoaded', () => {
        const apiEl = document.getElementById('apiBaseUrlDisplay');
        if (apiEl) apiEl.textContent = window.location.origin + '/api';

        const domainCtx = document.getElementById('domainChart');
        const activityCtx = document.getElementById('activityChart');

        if (domainCtx && typeof Chart !== 'undefined') {
          const domainLabels = ${raw(JSON.stringify(domainLabels))};
          const domainData = ${raw(JSON.stringify(domainData))};

          new Chart(domainCtx, {
            type: 'doughnut',
            data: {
              labels: domainLabels,
              datasets: [{
                data: domainData.every(v => v === 0) ? domainLabels.map(() => 1) : domainData,
                backgroundColor: ['#3b82f6', '#06b6d4', '#10b981', '#8b5cf6', '#f59e0b', '#ec4899'],
                borderColor: '#151d2a',
                borderWidth: 2
              }]
            },
            options: {
              responsive: true,
              maintainAspectRatio: false,
              plugins: {
                legend: {
                  position: 'right',
                  labels: { color: '#94a3b8', font: { family: 'Lexend', size: 11 } }
                }
              },
              cutout: '70%'
            }
          });
        }

        if (activityCtx && typeof Chart !== 'undefined') {
          new Chart(activityCtx, {
            type: 'bar',
            data: {
              labels: ['Inboxes', 'Messages', 'Domains', 'API Keys'],
              datasets: [{
                label: 'System Totals',
                data: [${totalInboxes}, ${totalMessages}, ${domains.length}, ${apiKeys.length}],
                backgroundColor: ['rgba(59, 130, 246, 0.7)', 'rgba(16, 185, 129, 0.7)', 'rgba(6, 182, 212, 0.7)', 'rgba(139, 92, 246, 0.7)'],
                borderColor: ['#3b82f6', '#10b981', '#06b6d4', '#8b5cf6'],
                borderWidth: 1,
                borderRadius: 6
              }]
            },
            options: {
              responsive: true,
              maintainAspectRatio: false,
              plugins: {
                legend: { display: false }
              },
              scales: {
                x: {
                  ticks: { color: '#94a3b8', font: { family: 'Lexend' } },
                  grid: { color: 'rgba(255, 255, 255, 0.05)' }
                },
                y: {
                  beginAtZero: true,
                  ticks: { color: '#94a3b8', font: { family: 'Lexend' } },
                  grid: { color: 'rgba(255, 255, 255, 0.05)' }
                }
              }
            }
          });
        }
      });
    </script>
    `
  })
}
