import { html } from 'hono/html'
import { Layout } from './layout'
import { Panel, StatCard, IconButton } from './components'
import type { Inbox } from '../db/queries'

export function DashboardPage({ 
  inboxes, domains, apiKeys, totalInboxes, totalMessages, currentPage, apiKeyFilter
}: { 
  inboxes: Inbox[]; domains: string[]; apiKeys: any[]; totalInboxes: number; totalMessages: number; currentPage: number; apiKeyFilter?: any
}) {
  const totalPages = Math.ceil(totalInboxes / 20) || 1
  const baseUrl = apiKeyFilter ? `/dashboard/apikeys/${apiKeyFilter.id}` : '/dashboard'

  return Layout({
    title: apiKeyFilter ? `Filtered by API Key` : 'Dashboard',
    session: true,
    children: html`
    <div class="dash-header">
      <div>
        <h2>${apiKeyFilter ? `API Key: ${apiKeyFilter.keyValue}` : 'Dashboard Overview'}</h2>
        <p>${apiKeyFilter ? `Showing ${totalInboxes} inboxes generated by this key` : 'Manage all disposable inboxes and API keys'}</p>
      </div>
      ${apiKeyFilter ? html`
        <a href="/dashboard" class="btn-primary" style="text-decoration:none"><i data-lucide="arrow-left" class="icon-inline" style="color:white;margin:0 8px 0 0"></i> Back to Dashboard</a>
      ` : ''}
    </div>

    <!-- Stats -->
    <div class="stats-grid">
      ${StatCard({ label: 'Total Inboxes', value: totalInboxes })}
      ${StatCard({ label: 'Total Messages', value: totalMessages })}
      ${StatCard({ label: 'Active Domains', value: domains.length })}
      ${StatCard({ label: 'API Keys', value: apiKeys.length })}
    </div>

    <!-- API Keys Panel -->
    ${!apiKeyFilter ? Panel({ title: 'API Keys & Permissions', icon: 'key', children: html`
      <form class="create-form" onsubmit="createApiKey(event)" style="margin-bottom:24px;">
        <div style="margin-bottom:20px; display:flex; flex-direction:column; gap:12px;">
          <label style="display:flex;align-items:center;gap:12px;cursor:pointer;padding:12px 16px;background:rgba(255,255,255,0.02);border-radius:8px;border:1px solid var(--border)">
            <input type="radio" name="domainScope" value="*" checked onchange="document.getElementById('specificDomains').style.display='none'" style="width:18px;height:18px;accent-color:var(--primary);cursor:pointer;" />
            <span style="font-weight:500;font-size:0.95rem">All Domains (*)</span>
          </label>
          <label style="display:flex;align-items:center;gap:12px;cursor:pointer;padding:12px 16px;background:rgba(255,255,255,0.02);border-radius:8px;border:1px solid var(--border)">
            <input type="radio" name="domainScope" value="specific" onchange="document.getElementById('specificDomains').style.display='flex'" style="width:18px;height:18px;accent-color:var(--primary);cursor:pointer;" />
            <span style="font-weight:500;font-size:0.95rem">Specific Domains</span>
          </label>
        </div>
        
        <div id="specificDomains" style="display:none;flex-direction:column;gap:12px;margin-bottom:20px;padding-left:24px;border-left:2px solid var(--border)">
          ${domains.map(d => html`
            <label style="display:flex;align-items:center;gap:12px;cursor:pointer;padding:8px 12px;background:rgba(255,255,255,0.03);border-radius:6px;border:1px solid var(--border)">
              <input type="checkbox" name="selectedDomains" value="${d}" style="width:16px;height:16px;accent-color:var(--primary);cursor:pointer;" />
              <span style="font-family:monospace;font-size:0.95rem;color:var(--text)">${d}</span>
            </label>
          `)}
        </div>
        
        <button type="submit" class="btn-primary" id="btnCreateKey">Generate Key</button>
      </form>

      <div class="inbox-list">
        ${!apiKeys || apiKeys.length === 0 ? html`<p style="color:var(--text-dim);text-align:center;padding:20px">No API keys generated yet.</p>` : ''}
        ${apiKeys && apiKeys.map(k => html`
          <div class="inbox-item" id="keyrow-${k.id}">
            <div class="inbox-info">
              <h4 style="color:var(--primary)">${k.keyValue}</h4>
              <p>Domains: <span style="color:#fff">${k.permittedDomains}</span> &nbsp;&bull;&nbsp; Created: ${new Date(k.createdAt).toLocaleDateString()}</p>
            </div>
            <div class="actions">
              <a href="/dashboard/apikeys/${k.id}" class="btn-icon" title="View Generated Inboxes"><i data-lucide="eye"></i></a>
              ${IconButton({ icon: 'trash-2', onclick: `delKey('${k.id}')`, title: 'Revoke Key', variant: 'danger' })}
            </div>
          </div>
        `)}
      </div>
    `}) : ''}

    <!-- Create Inbox -->
    ${!apiKeyFilter ? Panel({ title: 'Create Custom Inbox', icon: 'plus-circle', children: html`
      <form class="create-form" onsubmit="create(event)">
        <div class="input-group">
          <input type="text" id="local" placeholder="random (optional)" />
          <span class="at">@</span>
          <select id="domain">
            ${domains.map(d => html`<option value="${d}">${d}</option>`)}
          </select>
        </div>
        <button type="submit" class="btn-primary" id="btnCreate">Create Inbox</button>
      </form>
    `}) : ''}

    <!-- Inbox List -->
    ${Panel({ title: apiKeyFilter ? 'Generated Inboxes' : 'All Generated Inboxes', icon: 'list', children: html`
      <div class="inbox-list">
        ${inboxes.length === 0 ? html`<p style="color:var(--text-dim);text-align:center;padding:20px">No inboxes yet.</p>` : ''}
        ${inboxes.map(i => html`
          <div class="inbox-item" id="row-${i.address}">
            <div class="inbox-info">
              <h4><a href="/inbox/${encodeURIComponent(i.address)}">${i.address}</a></h4>
              <p>Created: ${new Date(i.createdAt).toLocaleString()}</p>
            </div>
            <div class="inbox-meta">
              <span class="badge">${i.messageCount || 0} msgs</span>
              <div class="actions">
                <a href="/inbox/${encodeURIComponent(i.address)}" class="btn-icon" title="View Inbox"><i data-lucide="eye"></i></a>
                ${IconButton({ icon: 'trash-2', onclick: `del('${i.address}')`, title: 'Delete', variant: 'danger' })}
              </div>
            </div>
          </div>
        `)}
      </div>

      <!-- Pagination -->
      ${totalPages > 1 ? html`
      <div style="display:flex; justify-content:center; align-items:center; gap:16px; margin-top:24px; padding-top:16px; border-top:1px solid var(--border)">
        <a href="${baseUrl}?page=${currentPage - 1}" class="btn-primary" style="${currentPage <= 1 ? 'pointer-events:none;opacity:0.5' : ''}">
          <i data-lucide="chevron-left" class="icon-inline"></i> Prev
        </a>
        
        <span style="color:var(--text-dim); font-size:0.9rem;">
          Page <strong>${currentPage}</strong> of ${totalPages}
        </span>
        
        <a href="${baseUrl}?page=${currentPage + 1}" class="btn-primary" style="${currentPage >= totalPages ? 'pointer-events:none;opacity:0.5' : ''}">
          Next <i data-lucide="chevron-right" class="icon-inline" style="margin-left:8px; margin-right:0"></i>
        </a>
      </div>
      ` : ''}
    `})}

    <script>
      function showToast(msg) {
        const t = document.getElementById('toast');
        t.textContent = msg; t.classList.add('show');
        setTimeout(() => t.classList.remove('show'), 3000);
      }
      
      async function create(e) {
        e.preventDefault();
        const btn = document.getElementById('btnCreate');
        btn.disabled = true; btn.textContent = 'Creating...';
        const local = document.getElementById('local').value;
        const domain = document.getElementById('domain').value;
        try {
          const r = await fetch('/dashboard/inboxes', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify({ local, domain })
          });
          if (r.ok) location.reload();
          else showToast('Failed to create inbox');
        } finally {
          btn.disabled = false; btn.textContent = 'Create Inbox';
        }
      }

      async function del(addr) {
        if (!confirm('Delete inbox ' + addr + '?')) return;
        const r = await fetch('/dashboard/inboxes/' + encodeURIComponent(addr), { method: 'DELETE' });
        if (r.ok) {
          const row = document.getElementById('row-' + addr);
          if (row) row.remove();
          showToast('Deleted ' + addr);
        } else {
          showToast('Failed to delete');
        }
      }

      async function createApiKey(e) {
        e.preventDefault();
        const btn = document.getElementById('btnCreateKey');
        btn.disabled = true; btn.textContent = 'Generating...';
        
        let domains = '*';
        const scope = document.querySelector('input[name="domainScope"]:checked').value;
        if (scope === 'specific') {
          const checked = Array.from(document.querySelectorAll('input[name="selectedDomains"]:checked')).map(cb => cb.value);
          if (checked.length > 0) domains = checked.join(',');
        }

        try {
          const r = await fetch('/dashboard/apikeys', {
            method: 'POST',
            headers: {'Content-Type':'application/json'},
            body: JSON.stringify({ domains })
          });
          if (r.ok) location.reload();
          else showToast('Failed to generate key');
        } finally {
          btn.disabled = false; btn.textContent = 'Generate Key';
        }
      }

      async function delKey(id) {
        if (!confirm('Revoke this API Key?')) return;
        const r = await fetch('/dashboard/apikeys/' + encodeURIComponent(id), { method: 'DELETE' });
        if (r.ok) {
          const row = document.getElementById('keyrow-' + id);
          if (row) row.remove();
          showToast('Key revoked');
        } else {
          showToast('Failed to revoke');
        }
      }

      async function logout() {
        await fetch('/auth/logout', {method:'POST'});
        location.href = '/login';
      }
    </script>
    `
  })
}
