// DO NOT edit this file directly — edit styles.css then rebuild
export const css = `*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#0b0f19;--bg2:#111827;--bg3:#1a2236;--border:#1e293b;--text:#e2e8f0;--text2:#94a3b8;--accent:#6366f1;--accent2:#818cf8;--green:#34d399;--red:#f87171;--orange:#fb923c;--radius:12px}
body{font-family:'Inter',-apple-system,sans-serif;background:var(--bg);color:var(--text);min-height:100vh}
a{color:var(--accent2);text-decoration:none}
button{cursor:pointer;border:none;font:inherit}
input,select{font:inherit}
.app-layout{display:flex;min-height:100vh}
.sidebar{width:260px;background:var(--bg2);border-right:1px solid var(--border);padding:24px 16px;display:flex;flex-direction:column;gap:24px;flex-shrink:0}
.sidebar-logo{font-size:22px;font-weight:800;background:linear-gradient(135deg,var(--accent),var(--accent2));-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:-0.5px}
.sidebar-nav{display:flex;flex-direction:column;gap:4px;flex:1}
.sidebar-nav a{display:flex;align-items:center;gap:12px;padding:10px 14px;border-radius:10px;color:var(--text2);font-size:14px;font-weight:500;transition:all .15s}
.sidebar-nav a:hover,.sidebar-nav a.active{background:var(--bg3);color:var(--text)}
.sidebar-nav a.active{background:var(--accent);color:#fff}
.sidebar-footer{padding-top:12px;border-top:1px solid var(--border)}
.sidebar-footer button{width:100%;padding:8px;border-radius:8px;background:transparent;color:var(--text2);font-size:13px;transition:all .15s}
.sidebar-footer button:hover{background:var(--bg3);color:var(--red)}
.main{flex:1;padding:32px 36px;overflow-y:auto}
.auth-page{display:flex;align-items:center;justify-content:center;min-height:100vh}
.auth-card{background:var(--bg2);border:1px solid var(--border);border-radius:16px;padding:40px;width:100%;max-width:400px}
.auth-card h1{font-size:28px;font-weight:800;text-align:center;margin-bottom:8px}
.auth-card p{text-align:center;color:var(--text2);font-size:14px;margin-bottom:28px}
.auth-input{width:100%;padding:12px 16px;background:var(--bg3);border:1px solid var(--border);border-radius:10px;color:var(--text);font-size:15px;outline:none;transition:border-color .15s}
.auth-input:focus{border-color:var(--accent)}
.auth-btn{width:100%;padding:12px;background:var(--accent);color:#fff;border-radius:10px;font-size:15px;font-weight:600;margin-top:12px;transition:.15s}
.auth-btn:hover{background:var(--accent2)}
.auth-error{color:var(--red);text-align:center;font-size:13px;margin-top:12px}
.dash-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:32px}
.dash-header h2{font-size:24px;font-weight:700}
.dash-stats{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px;margin-bottom:32px}
.stat-card{background:var(--bg2);border:1px solid var(--border);border-radius:var(--radius);padding:20px}
.stat-card .label{font-size:12px;color:var(--text2);text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}
.stat-card .value{font-size:28px;font-weight:700}
.panel{background:var(--bg2);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;margin-bottom:24px}
.panel-header{display:flex;align-items:center;justify-content:space-between;padding:16px 20px;border-bottom:1px solid var(--border)}
.panel-header h3{font-size:16px;font-weight:600}
.panel-body{padding:20px}
.btn{display:inline-flex;align-items:center;gap:8px;padding:10px 18px;border-radius:10px;font-size:14px;font-weight:600;transition:all .15s}
.btn-primary{background:var(--accent);color:#fff}.btn-primary:hover{background:var(--accent2)}
.btn-secondary{background:var(--bg3);color:var(--text)}.btn-secondary:hover{background:var(--border)}
.btn-danger{background:transparent;color:var(--red);border:1px solid var(--red)}.btn-danger:hover{background:var(--red);color:#fff}
.btn-sm{padding:6px 12px;font-size:12px}
.btn-icon{width:36px;height:36px;display:inline-flex;align-items:center;justify-content:center;border-radius:8px;background:var(--bg3);color:var(--text2);font-size:18px}
.btn-icon:hover{background:var(--border);color:var(--text)}
table{width:100%;border-collapse:collapse}
th{text-align:left;padding:12px 16px;font-size:12px;color:var(--text2);text-transform:uppercase;letter-spacing:.5px;border-bottom:1px solid var(--border)}
td{padding:14px 16px;font-size:14px;border-bottom:1px solid var(--border)}
tr:last-child td{border-bottom:none}
tr:hover td{background:var(--bg3)}
.badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600}
.badge-green{background:rgba(52,211,153,.15);color:var(--green)}
.badge-gray{background:var(--bg3);color:var(--text2)}
.empty-state{text-align:center;padding:40px 20px;color:var(--text2)}
.empty-state .icon{font-size:48px;margin-bottom:12px}
.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}
.hidden{display:none!important}
.toast{position:fixed;bottom:24px;right:24px;background:var(--bg2);border:1px solid var(--border);border-radius:12px;padding:12px 20px;font-size:14px;z-index:1000;animation:slideIn .3s ease}
@keyframes slideIn{from{transform:translateY(20px);opacity:0}to{transform:translateY(0);opacity:1}}
.msg-body{padding:20px;background:var(--bg);border-radius:8px;white-space:pre-wrap;line-height:1.6;max-height:500px;overflow-y:auto;font-family:'JetBrains Mono',monospace;font-size:13px}
.inbox-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}
.inbox-card{background:var(--bg3);border:1px solid var(--border);border-radius:var(--radius);padding:16px;cursor:pointer;transition:all .15s}
.inbox-card:hover{border-color:var(--accent);transform:translateY(-2px)}
.inbox-card .addr{font-size:15px;font-weight:600;margin-bottom:4px}
.inbox-card .meta{font-size:12px;color:var(--text2)}
@media(max-width:768px){.sidebar{width:100%;position:fixed;bottom:0;left:0;right:0;z-index:100;flex-direction:row;padding:12px 16px;border-right:none;border-top:1px solid var(--border)}.sidebar-logo,.sidebar-footer{display:none}.sidebar-nav{flex-direction:row;gap:2px}.sidebar-nav a{padding:8px 12px;font-size:12px}.main{padding:20px 16px;padding-bottom:80px}}`
